# 使用更小的基础镜像
FROM bitnami/python:3.13-debian-12

# 设置工作目录
WORKDIR /app

# 复制应用代码
COPY . .

# 安装依赖到指定目录
RUN pip install --no-cache-dir --prefix=/usr/local -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/


# 设置启动命令
CMD ["python", "/app/app.py"]
